version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: 'always'
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: bind
        source: ./dependencies/postgres/data
        target: /var/lib/postgresql/data/pgdata